[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps = 
    fastled/FastLED@^3.6.0
    Servo

[env:nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600
upload_speed = 115200
build_flags =
    -D SERIAL_DEBUG
    -D BAUD_RATE=9600
lib_deps = 
    fastled/FastLED@^3.6.0
    Servo
upload_port = /dev/cu.usbserial-2130